#lang racket
(require "../faster-minikanren/mk.rkt")
(require "commit.rkt")


;3way handshake
(define (test-3way-handshake)
  (define P `((new (name Sa))
              (store (variable Xsa) (name Sa))
              (out (name C) (pair-term (constant A) (pair-term (constant B) (variable Xsa))))
              (inp (name C) (variable Bp-Ap-Sbp-sXsap))
              (split ((variable Bp) (variable Ap-Sbp-sXsap)) (variable Bp-Ap-Sbp-sXsap) ((free (variable Bp-Ap-Sbp-sXsap)) (free (variable Xsa))))
              (free (variable Bp-Ap-Sbp-sXsap))
              (split ((variable Ap) (variable Sbp-sXsap)) (variable Ap-Sbp-sXsap) ((free (variable Ap-Sbp-sXsap)) (free (variable Bp)) (free (variable Xsa))))
              (free (variable Ap-Sbp-sXsap))
              (split ((variable Sbp) (variable sXsap)) (variable Sbp-sXsap) ((free (variable Sbp-sXsap)) (free (variable Ap)) (free (variable Bp)) (free (variable Xsa))))
              (free (variable Sbp-sXsap))
              (match (variable Ap) (constant A) ((free (variable Ap)) (free (variable Bp)) (free (variable Sbp)) (free (variable sXsap)) (free (variable Xsa))))
              (match (variable Bp) (constant B) ((free (variable Ap)) (free (variable Bp)) (free (variable Sbp)) (free (variable sXsap)) (free (variable Xsa))))
              (match (variable sXsap) (pair-term (variable Xsa) (constant 1)) ((free (variable Ap)) (free (variable Bp)) (free (variable Sbp)) (free (variable sXsap)) (free (variable Xsa))))
              (free (variable Ap))
              (free (variable Bp))
              (free (variable sXsap))
              (out (name C) (pair-term (constant A) (pair-term (constant B) (pair-term (pair-term (variable Xsa) (constant 1)) (pair-term (variable Sbp) (constant 1))))))
              ))
  (define Q `((new (name Sb))
              (inp (name C) (variable Aq-Bq-Xsaq))
              (split ((variable Aq) (variable Bq-Xsaq)) (variable Aq-Bq-Xsaq) ((free (variable Aq-Bq-Xsaq))))
              (free (variable Aq-Bq-Xsaq))
              (split ((variable Bq) (variable Xsaq)) (variable Bq-Xsaq) ((free (variable Bq-Xsaq))))
              (free (variable Bq-Xsaq))
              (match (variable Bq) (constant B) ((free (variable Bq)) (free (variable Aq)) (free (variable Xsaq))))
              (store (variable Sbq) (name Sb))
              (out (name C) (pair-term (constant B) (pair-term (variable Aq) (pair-term (variable Sbq) (pair-term (variable Xsaq) (constant 1))))))
              (inp (name C) (variable Aq2-Bq2-sSaq-sSbq))
              (split ((variable Aq2) (variable Bq2-sSaq-sSbq)) (variable Aq2-Bq2-sSaq-sSbq) ((free (variable Aq)) (free (variable Bq)) (free (variable Aq2-Bq2-sSaq-sSbq)) (free (variable Sbq))))
              (free (variable Aq2-Bq2-sSaq-sSbq))
              (split ((variable Bq2) (variable sSaq-sSbq)) (variable Bq2-sSaq-sSbq) ((free (variable Aq)) (free (variable Bq)) (free (variable Aq2)) (free (variable Bq2-sSaq-sSbq)) (free (variable Sbq))))
              (free (variable Bq2-sSaq-sSbq))
              (split ((variable sSaq) (variable sSbq)) (variable sSaq-sSbq) ((free (variable Aq)) (free (variable Bq)) (free (variable Aq2)) (free (variable Bq2)) (free (variable sSaq-sSbq)) (free (variable Sbq))))
              (free (variable sSaq-sSbq))
              (match (variable Aq) (variable Aq2) ((free (variable Aq)) (free (variable Bq)) (free (variable Aq2)) (free (variable Bq2)) (free (variable sSaq)) (free (variable sSbq)) (free (variable Sbq))))
              (match (variable Bq) (constant B) ((free (variable Aq)) (free (variable Bq)) (free (variable Aq2)) (free (variable Bq2)) (free (variable sSaq)) (free (variable sSbq)) (free (variable Sbq))))
              (match (variable sSaq) (pair-term (variable Xsaq) (constant 1)) ((free (variable Aq)) (free (variable Bq)) (free (variable Aq2)) (free (variable Bq2)) (free (variable sSaq)) (free (variable sSbq)) (free (variable Sbq))))
              (match (variable sSbq) (pair-term (variable Sbq) (constant 1)) ((free (variable Aq)) (free (variable Bq)) (free (variable Aq2)) (free (variable Bq2)) (free (variable sSaq)) (free (variable sSbq)) (free (variable Sbq))))
              (free (variable Aq2))
              (free (variable Bq))
              (free (variable sSaq))
              (free (variable sSbq))
              ))
  (define testcase `(parallel ,P ,Q))
  (define type-2calc `(composite-type-class (calc-type-class (calc C1)) (calc-type-class (calc C2))))
  (run* (x) (fresh (fin S) (== x `(,type-2calc /= ,testcase ->> ,fin : ,S)) (mcomm-process@ type-2calc testcase fin S))))

;SYN-flood
(define (test-syn-flood)
  (define Q `((new (name Sb))
              (inp (name C) (variable Aq-Bq-Xsaq))
              (split ((variable Aq) (variable Bq-Xsaq)) (variable Aq-Bq-Xsaq) ((free (variable Aq-Bq-Xsaq))))
              (free (variable Aq-Bq-Xsaq))
              (split ((variable Bq) (variable Xsaq)) (variable Bq-Xsaq) ((free (variable Bq-Xsaq))))
              (free (variable Bq-Xsaq))
              (match (variable Bq) (constant B) ((free (variable Bq)) (free (variable Aq)) (free (variable Xsaq))))
              (store (variable Sbq) (name Sb))
              (out (name C) (pair-term (constant B) (pair-term (variable Aq) (pair-term (variable Sbq) (pair-term (variable Xsaq) (constant 1))))))
              (inp (name C) (variable Aq2-Bq2-sSaq-sSbq))
              (split ((variable Aq2) (variable Bq2-sSaq-sSbq)) (variable Aq2-Bq2-sSaq-sSbq) ((free (variable Aq)) (free (variable Bq)) (free (variable Aq2-Bq2-sSaq-sSbq)) (free (variable Sbq))))
              (free (variable Aq2-Bq2-sSaq-sSbq))
              (split ((variable Bq2) (variable sSaq-sSbq)) (variable Bq2-sSaq-sSbq) ((free (variable Aq)) (free (variable Bq)) (free (variable Aq2)) (free (variable Bq2-sSaq-sSbq)) (free (variable Sbq))))
              (free (variable Bq2-sSaq-sSbq))
              (split ((variable sSaq) (variable sSbq)) (variable sSaq-sSbq) ((free (variable Aq)) (free (variable Bq)) (free (variable Aq2)) (free (variable Bq2)) (free (variable sSaq-sSbq)) (free (variable Sbq))))
              (free (variable sSaq-sSbq))
              (match (variable Aq) (variable Aq2) ((free (variable Aq)) (free (variable Bq)) (free (variable Aq2)) (free (variable Bq2)) (free (variable sSaq)) (free (variable sSbq)) (free (variable Sbq))))
              (match (variable Bq) (constant B) ((free (variable Aq)) (free (variable Bq)) (free (variable Aq2)) (free (variable Bq2)) (free (variable sSaq)) (free (variable sSbq)) (free (variable Sbq))))
              (match (variable sSaq) (pair-term (variable Xsaq) (constant 1)) ((free (variable Aq)) (free (variable Bq)) (free (variable Aq2)) (free (variable Bq2)) (free (variable sSaq)) (free (variable sSbq)) (free (variable Sbq))))
              (match (variable sSbq) (pair-term (variable Sbq) (constant 1)) ((free (variable Aq)) (free (variable Bq)) (free (variable Aq2)) (free (variable Bq2)) (free (variable sSaq)) (free (variable sSbq)) (free (variable Sbq))))
              (free (variable Aq2))
              (free (variable Bq))
              (free (variable sSaq))
              (free (variable sSbq)))
    )
  (define I `((new (name i)) (new (name s)) (out (name C) (pair-term (name i) (pair-term (constant B) (name s)))))
              )
  (define R `((inp (name C) (variable r)))
              )
  (define testcase `(parallel ,Q (parallel ,I ,R)))
  (define type-3calc `(composite-type-class (calc-type-class (calc C1)) (composite-type-class (calc-type-class (calc C2))(calc-type-class (calc C3)))))
  (run* (x) (fresh (fin S) (== x `(,type-3calc /= ,testcase ,fin : ,S)) (mcomm-process@ type-3calc testcase fin S))))
